### ISSUE TITLE
update map location (help)

### ISSUE THREAD

**Issue by johnpaulmedina** [angular-ui/ui-map#48]
im using an API call to load in person detail. I want to update the map center location once the details are returned from the api but i cant seem to get it to work.

Lead.get($state.params, function(data) {
		$scope.lead = data;
		$scope.mapOptions.center = new google.maps.LatLng(20.6700, -43.9400);
	});

I had already defined mapOptions within the controller scope and just trying to update the LatLng center but no luck. Any suggestions would be great!

**Comment by julesmoretti** [comment]
Plus one on with this. Thank you!

**Comment by julesmoretti** [comment]
Actually found the solution.

Say you have this in your html:

```
<div ui-map="myMapName" ui-options="newMapOptions" class="map-canvas"></div>
```

all you need in your controller is this:

```
$scope.myMapName.setCenter( new google.maps.LatLng( aLatitude, aLongitude) );
```

Try it out and let me know if it works for you too.
